### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by brooksdavis** [CTSRD-CHERI/cheribsd#2214]
- [ ] create releng/YY.MM branch
- [ ] create release/YY.MM tag
- [ ] copy releng/YY.MM snapshot build corresponding to the release/YY.MM to the release directories:
  - login to cheri-dist
  - make YY.MM directories for each of arm64/aarch64, arm64/aarch64c, riscv/riscv64, riscv/riscv64c
  - copy (cp -a) final release snapshot to each of /releases/MACHINE/MACHINE_ARCH/YY.MM
    - e.g. for the 24.05 release we did:
    `cd /var/www/download.cheribsd.org/releases/arm64/aarch64/24.05/`
     `cp -a ../../../../snapshots/releng/24.05/arm64/aarch64c/2024-07-19/* . `
    - NB: rename aarch64c memstick image to cheribsd-memstick-arm64-aarch64c-YY.MM.img.xz and update ftp/ symlink to match
    - NB2: at the current time (Fall 2024) only aarch64c has a large set of kernels
- [ ] update man.cheribsd.org (hosted cheri-dist)
  - copy /var/www/man.cheribsd.org/man/releng-YY.MM to release-YY.MM
  - add release-YY.MM and releng-YY.MM entries in /var/www/man.cheribsd.org/man/manpath.conf
- [ ] update index.html for cheribsd.org via PR to [CTSRD-CHERI/cheribsd-website.git](https://github.com/CTSRD-CHERI/cheribsd-website)
- [ ] send release annoucement via email and on both Slack instances
- [ ] update checklist in [CHERI Release: Template](https://github.com/orgs/CTSRD-CHERI/projects/18?pane=issue&itemId=76030146)
